package database;

import model.Administrator;
import model.Booking;
import model.Customer;
import model.RentalAgent;
import model.User;
import model.Vehicle;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class DatabaseHandler {

    private static final String JDBC_URL = "**********"; 
    private static final String DB_USER = "******";
    private static final String DB_PASSWORD = "****";

    private Connection connection;

    public DatabaseHandler() {
        try {

            Class.forName("oracle.jdbc.driver.OracleDriver");

            connection = DriverManager.getConnection(JDBC_URL, DB_USER, DB_PASSWORD);
            System.out.println("Connected to Oracle database successfully.");
        } catch (ClassNotFoundException e) {
            System.err.println("Oracle JDBC Driver not found.");
            e.printStackTrace();
        } catch (SQLException e) {
            System.err.println("Connection Failed! Check output console.");
            e.printStackTrace();
        }
    }

    public void createTables() {
        String createUsersTable = "CREATE TABLE Users ("
                + "user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "name VARCHAR2(100) NOT NULL, "
                + "email VARCHAR2(100) UNIQUE NOT NULL, "
                + "password VARCHAR2(100) NOT NULL, "
                + "role VARCHAR2(50) NOT NULL"
                + ")";

        String createVehiclesTable = "CREATE TABLE Vehicles ("
                + "vehicle_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "make VARCHAR2(50) NOT NULL, "
                + "model VARCHAR2(50) NOT NULL, "
                + "year NUMBER(4) NOT NULL, "
                + "availability_status VARCHAR2(20) NOT NULL, "
                + "rental_price NUMBER(10,2) NOT NULL"
                + ")";

        String createBookingsTable = "CREATE TABLE Bookings ("
                + "booking_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "customer_id NUMBER NOT NULL, "
                + "vehicle_id NUMBER NOT NULL, "
                + "rental_date DATE NOT NULL, "
                + "return_date DATE NOT NULL, "
                + "status VARCHAR2(20) NOT NULL, "
                + "FOREIGN KEY (customer_id) REFERENCES Users(user_id), "
                + "FOREIGN KEY (vehicle_id) REFERENCES Vehicles(vehicle_id)"
                + ")";

        try (Statement stmt = connection.createStatement()) {

            try {
                stmt.execute(createUsersTable);
                System.out.println("Users table created successfully.");
            } catch (SQLException e) {
                if (e.getErrorCode() == 955) { 
                    System.out.println("Users table already exists.");
                } else {
                    throw e;
                }
            }

            try {
                stmt.execute(createVehiclesTable);
                System.out.println("Vehicles table created successfully.");
            } catch (SQLException e) {
                if (e.getErrorCode() == 955) {
                    System.out.println("Vehicles table already exists.");
                } else {
                    throw e;
                }
            }

            try {
                stmt.execute(createBookingsTable);
                System.out.println("Bookings table created successfully.");
            } catch (SQLException e) {
                if (e.getErrorCode() == 955) {
                    System.out.println("Bookings table already exists.");
                } else {
                    throw e;
                }
            }

        } catch (SQLException e) {
            System.err.println("Error creating tables.");
            e.printStackTrace();
        }

        ensureDefaultUsers();

        populateDefaultVehicles();
    }

    private void ensureDefaultUsers() {

        String adminEmail = "admin@admin.com";
        if (getUserByEmail(adminEmail) == null) {
            User admin = new Administrator(0, "Default Admin", adminEmail, "12345");
            addUser(admin);
            System.out.println("Default administrator created.");
        } else {
            System.out.println("Default administrator already exists.");
        }

        String agentEmail = "rental@rental.com";
        if (getUserByEmail(agentEmail) == null) {
            User rentalAgent = new RentalAgent(0, "Default Rental Agent", agentEmail, "12345");
            addUser(rentalAgent);
            System.out.println("Default rental agent created.");
        } else {
            System.out.println("Default rental agent already exists.");
        }

        String customerEmail = "customer@customer.com";
        if (getUserByEmail(customerEmail) == null) {
            User customer = new Customer(0, "Default Customer", customerEmail, "12345");
            addUser(customer);
            System.out.println("Default customer created.");
        } else {
            System.out.println("Default customer already exists.");
        }
    }

    public void populateDefaultVehicles(){
        String checkSql = "SELECT COUNT(*) AS total FROM Vehicles";
        try (Statement stmt = connection.createStatement()) {
            ResultSet rs = stmt.executeQuery(checkSql);
            if(rs.next()){
                int count = rs.getInt("total");
                if(count == 0){

                    String insertSql = "INSERT INTO Vehicles (make, model, year, availability_status, rental_price) VALUES (?, ?, ?, ?, ?)";
                    try (PreparedStatement pstmt = connection.prepareStatement(insertSql)) {

                        List<Vehicle> defaultVehicles = getDefaultVehicles();
                        for(Vehicle v : defaultVehicles){
                            pstmt.setString(1, v.getMake());
                            pstmt.setString(2, v.getModel());
                            pstmt.setInt(3, v.getYear());
                            pstmt.setString(4, v.getAvailabilityStatus());
                            pstmt.setDouble(5, v.getRentalPrice());
                            pstmt.addBatch();
                        }
                        pstmt.executeBatch();
                        System.out.println("Default vehicles added to the database.");
                    }
                } else {
                    System.out.println("Vehicles already exist in the database.");
                }
            }
        } catch (SQLException e) {
            System.err.println("Error checking or populating default vehicles.");
            e.printStackTrace();
        }
    }

    private List<Vehicle> getDefaultVehicles(){
        List<Vehicle> vehicles = new ArrayList<>();
        vehicles.add(new Vehicle(0, "Toyota", "Camry", 2020, "Available", 90.0));
        vehicles.add(new Vehicle(0, "Ford", "Explorer", 2019, "Available", 110.0));
        vehicles.add(new Vehicle(0, "Honda", "Civic", 2021, "Available", 95.0));
        vehicles.add(new Vehicle(0, "Chevrolet", "Malibu", 2018, "Available", 85.0));
        vehicles.add(new Vehicle(0, "Tesla", "Model S", 2022, "Available", 200.0));
        vehicles.add(new Vehicle(0, "BMW", "X5", 2020, "Available", 150.0));
        vehicles.add(new Vehicle(0, "Audi", "A4", 2019, "Available", 130.0));
        vehicles.add(new Vehicle(0, "Mercedes-Benz", "C-Class", 2021, "Available", 140.0));
        vehicles.add(new Vehicle(0, "Hyundai", "Elantra", 2017, "Available", 80.0));
        vehicles.add(new Vehicle(0, "Kia", "Sorento", 2020, "Available", 100.0));

        return vehicles;
    }

    public void addUser(User user) {
        String sql = "INSERT INTO Users (name, email, password, role) VALUES (?, ?, ?, ?)";
        try (PreparedStatement pstmt = connection.prepareStatement(sql)) {
            pstmt.setString(1, user.getName());
            pstmt.setString(2, user.getEmail());
            pstmt.setString(3, user.getPassword());
            pstmt.setString(4, user.getRole());
            pstmt.executeUpdate();
            System.out.println("User added successfully.");
        } catch (SQLException e) {
            System.err.println("Error adding user.");
            e.printStackTrace();
        }
    }

    public void removeUser(int userId) {
        String sql = "DELETE FROM Users WHERE user_id = ?";
        try (PreparedStatement pstmt = connection.prepareStatement(sql)) {
            pstmt.setInt(1, userId);
            int rowsDeleted = pstmt.executeUpdate();
            if(rowsDeleted > 0){
                System.out.println("User deleted successfully.");
            } else {
                System.out.println("No user found with the provided ID.");
            }
        } catch (SQLException e) {
            System.err.println("Error deleting user.");
            e.printStackTrace();
        }
    }

    public void updateUser(User user) {
        String sql = "UPDATE Users SET name = ?, email = ?, password = ?, role = ? WHERE user_id = ?";
        try (PreparedStatement pstmt = connection.prepareStatement(sql)) {
            pstmt.setString(1, user.getName());
            pstmt.setString(2, user.getEmail());
            pstmt.setString(3, user.getPassword());
            pstmt.setString(4, user.getRole());
            pstmt.setInt(5, user.getUserId());
            int rowsUpdated = pstmt.executeUpdate();
            if(rowsUpdated > 0){
                System.out.println("User updated successfully.");
            } else {
                System.out.println("No user found with the provided ID.");
            }
        } catch (SQLException e) {
            System.err.println("Error updating user.");
            e.printStackTrace();
        }
    }

    public User getUser(int userId) {
        String sql = "SELECT * FROM Users WHERE user_id = ?";
        try (PreparedStatement pstmt = connection.prepareStatement(sql)) {
            pstmt.setInt(1, userId);
            ResultSet rs = pstmt.executeQuery();
            if(rs.next()){
                String role = rs.getString("role");
                String name = rs.getString("name");
                String email = rs.getString("email");
                String password = rs.getString("password");
                switch(role){
                    case "Customer":
                        return new Customer(userId, name, email, password);
                    case "RentalAgent":
                        return new RentalAgent(userId, name, email, password);
                    case "Administrator":
                        return new Administrator(userId, name, email, password);
                    default:
                        return null;
                }
            }
        } catch (SQLException e) {
            System.err.println("Error fetching user.");
            e.printStackTrace();
        }
        return null;
    }

    public User getUserByEmail(String email) {
        String sql = "SELECT * FROM Users WHERE email = ?";
        try (PreparedStatement pstmt = connection.prepareStatement(sql)) {
            pstmt.setString(1, email);
            ResultSet rs = pstmt.executeQuery();
            if(rs.next()){
                int userId = rs.getInt("user_id");
                String role = rs.getString("role");
                String name = rs.getString("name");
                String password = rs.getString("password");
                switch(role){
                    case "Customer":
                        return new Customer(userId, name, email, password);
                    case "RentalAgent":
                        return new RentalAgent(userId, name, email, password);
                    case "Administrator":
                        return new Administrator(userId, name, email, password);
                    default:
                        return null;
                }
            }
        } catch (SQLException e) {
            System.err.println("Error fetching user by email.");
            e.printStackTrace();
        }
        return null;
    }

    public List<User> getAllUsers() {
        String sql = "SELECT * FROM Users";
        List<User> users = new ArrayList<>();
        try (Statement stmt = connection.createStatement()) {
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()){
                int userId = rs.getInt("user_id");
                String role = rs.getString("role");
                String name = rs.getString("name");
                String email = rs.getString("email");
                String password = rs.getString("password");
                switch(role){
                    case "Customer":
                        users.add(new Customer(userId, name, email, password));
                        break;
                    case "RentalAgent":
                        users.add(new RentalAgent(userId, name, email, password));
                        break;
                    case "Administrator":
                        users.add(new Administrator(userId, name, email, password));
                        break;
                    default:

                        break;
                }
            }
        } catch (SQLException e) {
            System.err.println("Error fetching users.");
            e.printStackTrace();
        }
        return users;
    }

    public void addVehicle(Vehicle vehicle) {
        String sql = "INSERT INTO Vehicles (make, model, year, availability_status, rental_price) VALUES (?, ?, ?, ?, ?)";
        try (PreparedStatement pstmt = connection.prepareStatement(sql)) {
            pstmt.setString(1, vehicle.getMake());
            pstmt.setString(2, vehicle.getModel());
            pstmt.setInt(3, vehicle.getYear());
            pstmt.setString(4, vehicle.getAvailabilityStatus());
            pstmt.setDouble(5, vehicle.getRentalPrice());
            pstmt.executeUpdate();
            System.out.println("Vehicle added successfully.");
        } catch (SQLException e) {
            System.err.println("Error adding vehicle.");
            e.printStackTrace();
        }
    }

    public void removeVehicle(int vehicleId) {
        String sql = "DELETE FROM Vehicles WHERE vehicle_id = ?";
        try (PreparedStatement pstmt = connection.prepareStatement(sql)) {
            pstmt.setInt(1, vehicleId);
            int rowsDeleted = pstmt.executeUpdate();
            if(rowsDeleted > 0){
                System.out.println("Vehicle deleted successfully.");
            } else {
                System.out.println("No vehicle found with the provided ID.");
            }
        } catch (SQLException e) {
            System.err.println("Error deleting vehicle.");
            e.printStackTrace();
        }
    }

    public void updateVehicle(Vehicle vehicle) {
        String sql = "UPDATE Vehicles SET make = ?, model = ?, year = ?, availability_status = ?, rental_price = ? WHERE vehicle_id = ?";
        try (PreparedStatement pstmt = connection.prepareStatement(sql)) {
            pstmt.setString(1, vehicle.getMake());
            pstmt.setString(2, vehicle.getModel());
            pstmt.setInt(3, vehicle.getYear());
            pstmt.setString(4, vehicle.getAvailabilityStatus());
            pstmt.setDouble(5, vehicle.getRentalPrice());
            pstmt.setInt(6, vehicle.getVehicleId());
            int rowsUpdated = pstmt.executeUpdate();
            if(rowsUpdated > 0){
                System.out.println("Vehicle updated successfully.");
            } else {
                System.out.println("No vehicle found with the provided ID.");
            }
        } catch (SQLException e) {
            System.err.println("Error updating vehicle.");
            e.printStackTrace();
        }
    }

    public Vehicle getVehicle(int vehicleId) {
        String sql = "SELECT * FROM Vehicles WHERE vehicle_id = ?";
        try (PreparedStatement pstmt = connection.prepareStatement(sql)) {
            pstmt.setInt(1, vehicleId);
            ResultSet rs = pstmt.executeQuery();
            if(rs.next()){
                String make = rs.getString("make");
                String model = rs.getString("model");
                int year = rs.getInt("year");
                String availabilityStatus = rs.getString("availability_status");
                double rentalPrice = rs.getDouble("rental_price");
                return new Vehicle(vehicleId, make, model, year, availabilityStatus, rentalPrice);
            }
        } catch (SQLException e) {
            System.err.println("Error fetching vehicle.");
            e.printStackTrace();
        }
        return null;
    }

    public List<Vehicle> getAllVehicles() {
        String sql = "SELECT * FROM Vehicles";
        List<Vehicle> vehicles = new ArrayList<>();
        try (Statement stmt = connection.createStatement()) {
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()){
                int vehicleId = rs.getInt("vehicle_id");
                String make = rs.getString("make");
                String model = rs.getString("model");
                int year = rs.getInt("year");
                String availabilityStatus = rs.getString("availability_status");
                double rentalPrice = rs.getDouble("rental_price");
                vehicles.add(new Vehicle(vehicleId, make, model, year, availabilityStatus, rentalPrice));
            }
        } catch (SQLException e) {
            System.err.println("Error fetching vehicles.");
            e.printStackTrace();
        }
        return vehicles;
    }

    public void addBooking(Booking booking) {
        String sql = "INSERT INTO Bookings (customer_id, vehicle_id, rental_date, return_date, status) VALUES (?, ?, ?, ?, ?)";
        try (PreparedStatement pstmt = connection.prepareStatement(sql)) {
            pstmt.setInt(1, booking.getCustomerId());
            pstmt.setInt(2, booking.getVehicleId());
            pstmt.setDate(3, booking.getRentalDate());
            pstmt.setDate(4, booking.getReturnDate());
            pstmt.setString(5, booking.getStatus());
            pstmt.executeUpdate();
            System.out.println("Booking added successfully.");
        } catch (SQLException e) {
            System.err.println("Error adding booking.");
            e.printStackTrace();
        }
    }

    public void removeBooking(int bookingId) {
        String sql = "DELETE FROM Bookings WHERE booking_id = ?";
        try (PreparedStatement pstmt = connection.prepareStatement(sql)) {
            pstmt.setInt(1, bookingId);
            int rowsDeleted = pstmt.executeUpdate();
            if(rowsDeleted > 0){
                System.out.println("Booking deleted successfully.");
            } else {
                System.out.println("No booking found with the provided ID.");
            }
        } catch (SQLException e) {
            System.err.println("Error deleting booking.");
            e.printStackTrace();
        }
    }

    public void updateBooking(Booking booking) {
        String sql = "UPDATE Bookings SET customer_id = ?, vehicle_id = ?, rental_date = ?, return_date = ?, status = ? WHERE booking_id = ?";
        try (PreparedStatement pstmt = connection.prepareStatement(sql)) {
            pstmt.setInt(1, booking.getCustomerId());
            pstmt.setInt(2, booking.getVehicleId());
            pstmt.setDate(3, booking.getRentalDate());
            pstmt.setDate(4, booking.getReturnDate());
            pstmt.setString(5, booking.getStatus());
            pstmt.setInt(6, booking.getBookingId());
            int rowsUpdated = pstmt.executeUpdate();
            if(rowsUpdated > 0){
                System.out.println("Booking updated successfully.");
            } else {
                System.out.println("No booking found with the provided ID.");
            }
        } catch (SQLException e) {
            System.err.println("Error updating booking.");
            e.printStackTrace();
        }
    }

    public Booking getBooking(int bookingId) {
        String sql = "SELECT * FROM Bookings WHERE booking_id = ?";
        try (PreparedStatement pstmt = connection.prepareStatement(sql)) {
            pstmt.setInt(1, bookingId);
            ResultSet rs = pstmt.executeQuery();
            if(rs.next()){
                int customerId = rs.getInt("customer_id");
                int vehicleId = rs.getInt("vehicle_id");
                Date rentalDate = rs.getDate("rental_date");
                Date returnDate = rs.getDate("return_date");
                String status = rs.getString("status");
                return new Booking(bookingId, customerId, vehicleId, rentalDate, returnDate, status);
            }
        } catch (SQLException e) {
            System.err.println("Error fetching booking.");
            e.printStackTrace();
        }
        return null;
    }

    public List<Booking> getAllBookings() {
        String sql = "SELECT * FROM Bookings";
        List<Booking> bookings = new ArrayList<>();
        try (Statement stmt = connection.createStatement()) {
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()){
                int bookingId = rs.getInt("booking_id");
                int customerId = rs.getInt("customer_id");
                int vehicleId = rs.getInt("vehicle_id");
                Date rentalDate = rs.getDate("rental_date");
                Date returnDate = rs.getDate("return_date");
                String status = rs.getString("status");
                bookings.add(new Booking(bookingId, customerId, vehicleId, rentalDate, returnDate, status));
            }
        } catch (SQLException e) {
            System.err.println("Error fetching bookings.");
            e.printStackTrace();
        }
        return bookings;
    }

    public void closeConnection() {
        if (connection != null) {
            try {
                connection.close();
                System.out.println("Database connection closed.");
            } catch (SQLException e) {
                System.err.println("Error closing connection.");
                e.printStackTrace();
            }
        }
    }
}